# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.srcs/sources_1/bd/system/ip/system_sys_rgmii_0/system_sys_rgmii_0.xci
# IP: The module: 'system_sys_rgmii_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.srcs/sources_1/bd/system/ip/system_sys_rgmii_0/system_sys_rgmii_0.xci
# IP: The module: 'system_sys_rgmii_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dator2/Documents/clean_fw_folder/antsdr-fw-patch/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_sys_rgmii_0/synth/system_sys_rgmii_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_rgmii_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
