# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dator2/Documents/fw-antsdr-version-10/plutosdr-fw/hdl/projects/e200/e200.srcs/sources_1/bd/system/ip/system_axi_dmac_0_0/system_axi_dmac_0_0.xci
# IP: The module: 'system_axi_dmac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/fw-antsdr-version-10/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_axi_dmac_0_0/system_axi_dmac_0_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_dmac_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dator2/Documents/fw-antsdr-version-10/plutosdr-fw/hdl/projects/e200/e200.srcs/sources_1/bd/system/ip/system_axi_dmac_0_0/system_axi_dmac_0_0.xci
# IP: The module: 'system_axi_dmac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/fw-antsdr-version-10/plutosdr-fw/hdl/projects/e200/e200.gen/sources_1/bd/system/ip/system_axi_dmac_0_0/system_axi_dmac_0_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_dmac_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
