# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks.xci
# IP: The module: 'gen_clks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks.xci
# IP: The module: 'gen_clks' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/dator2/Documents/antsdr_standalone/hdl/projects/antsdre200/ip/gen_clks/gen_clks_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clks'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
